# Generated by Django 4.1.3 on 2022-11-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('duration', models.FloatField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.artist')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.genre')),
            ],
        ),
    ]
