# Generated by Django 4.1.3 on 2022-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='myapp.playlist'),
        ),
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
