# Generated by Django 4.1.3 on 2022-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_song_album_remove_song_genre_song_album_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='myapp.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='myapp.artist'),
        ),
    ]
