# Generated by Django 4.1.3 on 2022-11-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_song_album_id_remove_song_artist_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
